### ISSUE TITLE
Change power supply mode

### ISSUE THREAD

**Issue by MhlTheOne** [svenerbe/ecoflow_dynamic_power_adjustment#5]
It would be very nice if you could switch the power supply mode between power supply and power storage.

**Comment by MhlTheOne** [comment]
I use the following workaround: I set the automation on false. But here is some stupid behavior from Ecostream:
If solar input more than 600W, it will be throttled, because the it's limited to battery.

For this case i decided to set and increase an fix PermanentWatts value. For this i use automation false with value and change the following lines:
        if not Automation:
            NewPermanentWatts= 0
in:
        if not Automation:
            NewPermanentWatts = TotalPower * 10

**Comment by svenerbe** [comment]
not an issue

**Comment by MhlTheOne** [comment]
I don't need to change the supply priority anymore, because I use above workaround to set an fix new output.
