### ISSUE TITLE
Script adds the sent value to the setting, not replacing it

### ISSUE THREAD

**Issue by yoginaut** [svenerbe/ecoflow_dynamic_power_adjustment#8]
He everybody,
I managed to get the script running using the description, thanks a lot for providing it!
I can see that it is working somehow but not as I expect it to work:
every time the script sends a value to my powerstream in the powerstream  settings the value is not replaced but added.
Example: the current value in the Ecoflow app under Household power demand shows 320W. The HA Automation triggers and the sent value is 15. In the app the value changes to 335W and not to 15W. So over time the powerstream setting always goes to 600W.
I would expect that the value changes to the sent 15W.

Any idea why this happens?

**Comment by svenerbe** [comment]
"The script functions as intended! Its purpose is to ensure minimal power flow to the grid, ideally achieving zero wattage. Essentially, your power sensor captures data regarding power exchanges with the grid and transmits it to the service. The service then calculates the variance in power, supplementing it with your household's current power consumption."

**Comment by yoginaut** [comment]
ok, I had a twist in my brain. If the current value is negative the script also sends a negative value to the Powerstream. So as you said, works as intended!
Thank you 👍
