### ISSUE TITLE
Use current inverter output and not permanent watt

### ISSUE THREAD

**Issue by MhlTheOne** [svenerbe/ecoflow_dynamic_power_adjustment#9]
I use the setting that if battery full and solar power is over current consumption, that all solar power is given to grid.

In this case the script reduce the permanent power in steps to 0W (because i currently feed into grid).

When the solar power decreases and i have grid supply again, the permanent power is increased in steps.
It makes more sense to use the current inverter output than the permanent watts for new calculation.

Do you known the right parameter for this?

Example:
Solar power is 400 W and goes full in grid, current consumption is 300W the script reduce permanent watts to 0.
If the solar power goes down to 250W the script get an different of 50W for totalpower and needs 6 updates to increase the permanent watts from 0 to 300W.

**Comment by MhlTheOne** [comment]
I believe invOutputWatts is the right param.

I change the following lines:
Line 128: `    quotas = ["20_1.permanentWatts"]` in `    quotas = ["20_1.invOutputWatts"]`
Line 134: `            cur_permanentWatts = round(payload.json()['data']['20_1.permanentWatts'] / 10)` in `            cur_permanentWatts = round(payload.json()['data']['20_1.invOutputWatts'] / 10)`

**Comment by svenerbe** [comment]
I'm not sure if i understand this issue. the script needs just the current grid consumption and will add this to permanentwatts. nothing else.

**Comment by MhlTheOne** [comment]
But this is an mistake, if you deactivate the option "Einspeisekontrolle / Feed-in control".

In this case if the battery is full, the total solar power is given to grid and the script reduce the permanentwatts to zero, if solar power is over current consumption.
If the solar power decrease under the current cunsumption, the script add the difference to 0 and not to the current feed in, see example above.

**Comment by svenerbe** [comment]
interesting, i have deactivate Feed-in control  as well - but i set if my  battery is nearly full 20_1.permanentWatts to 600 per ha automation.

**Comment by MhlTheOne** [comment]
In this case you don't have this issue. 
Otherwise the invOutputWatts is the better option to use.
